name: Pygments

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Test package
      run: pytest -W error

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install regex
      run: python -m pip install regex
    - name: Run make check
      run: make check
    - name: Fail if the basic checks failed
      run: make check
      if: runner.os == 'Linux'

  check-mapfiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install regex
      run: python -m pip install regex
    - name: Regenerate mapfiles
      run: make mapfiles
    - name: Fail if mapfiles changed
      run: |
        if git ls-files -m | grep mapping; then
          echo 'Please run "make mapfiles" and add the changes to a commit.'
          exit 1
        fi

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install regex
      run: python -m pip install regex
    - name: Check out regexlint
      run: git clone https://github.com/pygments/regexlint
    - name: Run regexlint
      run: make regexlint REGEXLINT=`pwd`/regexlint
